# Generated by Django 2.1.4 on 2018-12-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_time',
            new_name='create_time',
        ),
    ]
